#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SMTDroid.Resource", IsApplication=true)]

namespace SMTDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int btEvents = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int btEventsAttended = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int btLogin = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int btLogout = 2131034131;
			
			// aapt resource value: 0x7f050010
			public const int btPeople = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int btPeopleMet = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int listEvents = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int listEventsAttended = 2131034121;
			
			// aapt resource value: 0x7f05001c
			public const int listFutureEvents = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int listPeople = 2131034132;
			
			// aapt resource value: 0x7f050007
			public const int listPeopleAttending = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int listPeopleMet = 2131034133;
			
			// aapt resource value: 0x7f050005
			public const int tbAttend = 2131034117;
			
			// aapt resource value: 0x7f050018
			public const int textJobTitle = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int textName = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int textNextEvent = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int textNotes = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int textOrganisation = 2131034137;
			
			// aapt resource value: 0x7f050006
			public const int textPeopleAttending = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int textView1 = 2131034122;
			
			// aapt resource value: 0x7f05001b
			public const int toggleContactMet = 2131034139;
			
			// aapt resource value: 0x7f050003
			public const int txtDateTime = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int txtDescription = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int txtErrorMessage = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int txtEventName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int txtLocation = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int txtPassword = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int txtURL = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int txtUsername = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Event = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Events = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventsAttended = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int People = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PeopleMet = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Person = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
